homeassistant:
  customize:                                   !include customize.yaml
  elevation:                                   85
  latitude:                                    !secret latitude
  longitude:                                   !secret longitude
  name:                                        PandaPad
  packages:                                    !include_dir_named packages
  time_zone:                                   America/New_York
  unit_system:                                 imperial
  auth_providers:
    - type:                                    homeassistant
    - type:                                    trusted_networks
    - type:                                    legacy_api_password

cloud:
config:
conversation:
default_config:

device_tracker:
  - platform:                                  google_maps
    username:                                  !secret google_maps_username
    password:                                  !secret google_maps_password
  - platform:                                  ping
    count:                                     5
    hosts:
      oneplus_one:                             192.168.1.64
      galaxy_s5:                               192.168.1.166

discovery:
ecobee:
  api_key: !secret ecobee_api_key
frontend:                                      !include frontend.yaml
googlehome:
  devices:
    - host: 192.168.1.158
      track_alarms: True
    - host: 192.168.1.163
      track_alarms: True
    - host: 192.168.1.164
      track_alarms: True
group:                                         !include groups.yaml
history:

http:
  api_password:                                !secret http_password
  base_url:                                    panda-home.duckdns.org
  trusted_networks:
    - 172.30.32.0/23
    - 127.0.0.1
    - 192.168.1.0/24
  ip_ban_enabled:                              True
  login_attempts_threshold:                    10

logbook:

logger:
  default:                                     info
  logs:
    homeassistant.components.mqtt:             debug

map:

mqtt:
  broker:                                      192.168.1.200
  port:                                        1883
  client_id:                                   PandaPad_Main
  username:                                    !secret mqtt_user
  password:                                    !secret mqtt_password
  discovery:                                   true
  discovery_prefix:                            homeassistant

panel_iframe:
  nodered:
    title:                                     'Node-RED'
    url:                                       'https://panda-node-red.duckdns.org/'
    icon:                                      mdi:sitemap

person:
recorder:
  db_url:                                      !secret db_url
  purge_interval:                              1
  purge_keep_days:                             14

sun:
system_health:

tts:
  - platform:                                  google

updater:
  include_used_components:                     true

zwave:
  usb_path:                                    /dev/serial/by-id/usb-0658_0200-if00
  device_config:
    light.ge_14294_inwall_smart_dimmer_level:
      refresh_value:                           true
      delay:                                   5
