homeassistant:
  packages: !include_dir_named packages
  external_url: !secret external_url
  allowlist_external_dirs:
    - "/config"
    - "/config/motion"

automation: !include my_automations.yaml
config:
conversation:
cover:
  - platform: mqtt
    name: "Garage Door"
    availability:
      - topic: "Garage/OUT/STATUS"
    command_topic: "Garage/IN/STATE"
    state_topic: "Garage/OUT/STATE"
    payload_open: "open"
    payload_close: "close"
    payload_stop: "stop"
    state_closed: "CLOSED"
    state_open: "OPEN"
    json_attributes_topic: "Garage/OUT/JSON"
default_config:

discovery:
folder_watcher:
  - folder: /config
    patterns:
      - "*.yaml"
history:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.17.0.0/24

input_boolean:
  erin_away:
    name: "Erin is Away"
    initial: off
  game_night:
    name: "Game Night"
  vampire_mode:
    name: "Vampire Mode"
  hold_garage_open:
    name: "Hold Garage Door Open"
  nathan_away:
      name: "Nathan is Away"
  movie_mode:
    name: "Movie mode"
  hosting_mode:
    name: "Hosting Guests"

logbook:

logger:
  default: info

map:
mobile_app:

notify:
  - name: telegram_nathan
    platform: telegram
    chat_id: -355834039
  - name: telegram_erin
    platform: telegram
    chat_id: 728102599

person:
recorder:
  purge_keep_days: 7

script: !include my_scripts.yaml
sensor:
  - platform: github
    access_token: !secret github_token
    repositories:
      - path: "zybron/HomeAssistantConfig"
  - platform: template
    sensors:
      erin_location:
        friendly_name: "Erin's Location"
        value_template: "{{ [states.person.erin.attributes.latitude, states.person.erin.attributes.longitude] }}"
      nathan_location:
        friendly_name: "Nathan's Location"
        value_template: "{{ [states.person.nathan.attributes.latitude, states.person.nathan.attributes.longitude] }}"
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
  - platform: tautulli
    api_key: !secret tautulli_api_key
    host: !secret tautulli_host

shell_command:
  disco_off: echo -e -n '\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51' > /dev/ttyACM0
  disco_on: echo -e -n '\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50' > /dev/ttyACM0
  health_check: curl --retry 3 https://hc-ping.com/33aee216-ff26-47ee-9627-1e29985f0336
  pull_config: cd /config && git pull
sun:
system_health:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    parse_mode: html
    allowed_chat_ids:
      - 749282427
      - 728102599
      - -1001184476815
      - -355834039

tts:
  - platform: google_translate

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    units: 'us'
    mode: 'daily'

zone:
  - name: "Home"
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 200
    icon: mdi:home
