homeassistant:
  customize: !include customize.yaml
  elevation: 85
  latitude: !secret latitude
  longitude: !secret longitude
  name: PandaPad
  packages: !include_dir_named packages
  time_zone: America/New_York
  unit_system: imperial

camera:
  - platform: mjpeg
    mjpeg_url: !secret entryway_cam_url
    name: 'Entryway'
  - platform: mjpeg
    mjpeg_url: !secret kitchen_cam_url
    name: 'Kitchen'
  - platform: mjpeg
    mjpeg_url: !secret master_cam_url
    name: 'Master Bedroom'
  - platform: mjpeg
    mjpeg_url: !secret garage_cam_url
    name: 'Garage'
  - platform: mjpeg
    mjpeg_url: !secret livingroom_cam_url
    name: 'Livingroom'

config:
conversation:

default_config:

discovery:

history:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 10

image_processing:
  - platform: tensorflow
    source:
      - entity_id: camera.entryway
      - entity_id: camera.living_room
      - entity_id: camera.master_bedroom
      - entity_id: camera.garage
      - entity_id: camera.kitchen
    file_out:
      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      graph: /config/tensorflow/models/efficientdet_d7_coco17_tpu-32/
      categories:
        - category: person

logbook:

logger:
  default: info

map:
mobile_app:

person:
recorder:
  purge_interval: 1
  purge_keep_days: 7

sensor:
  - platform: waze_travel_time
    origin: zone.home
    destination: zone.work
    region: "US"
    name: "Work Travel Time"

sun:
system_health:

tts:
  - platform: google_translate

updater:
  include_used_components: true

zone:
  - name: "Home"
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 200
    icon: mdi:home
