homeassistant:
  packages: !include_dir_named packages
  external_url: "https://ha.zybron.com"
  allowlist_external_dirs:
    - "/config"
    - "/config/motion"

automation: !include my_automations.yaml
config:
conversation:

default_config:

discovery:
folder_watcher:
  - folder: /config
    patterns:
      - '*.yaml'
  - folder: /config/packages
    patterns:
      - '*.yaml'
history:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.17.0.0/24

logbook:

logger:
  default: info

map:
mobile_app:

person:
recorder:
  purge_keep_days: 7

script: !include my_scripts.yaml
sun:
system_health:

tts:
  - platform: google_translate


zone:
  - name: "Home"
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 200
    icon: mdi:home
