homeassistant:
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - "/config"
    - "/config/motion"

config:
conversation:

default_config:

discovery:

history:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.17.0.0/24

logbook:

logger:
  default: info

map:
mobile_app:

person:
recorder:
  purge_keep_days: 7

sensor:
  - platform: waze_travel_time
    origin: zone.home
    destination: zone.work
    region: "US"
    name: "Work Travel Time"

sun:
system_health:

tts:
  - platform: google_translate

updater:
  include_used_components: true

zone:
  - name: "Home"
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 200
    icon: mdi:home
