homeassistant:
  # Name of the location where Home Assistant is running
  name:                                        PandaPad
  # Location required to calculate the time the sun rises and sets
  latitude:                                    !secret latitude
  longitude:                                   !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation:                                   85
  # metric for Metric, imperial for Imperial
  unit_system:                                 imperial
  # Pick yours from here:                      http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone:                                   America/New_York
  # customizations
  packages:                                    !include_dir_named packages
  customize:                                   !include customize.yaml

group:                                         !include groups.yaml
automation:                                    !include_dir_merge_list automations/
script:                                        !include scripts.yaml
sensor:                                        !include sensors.yaml
switch:                                        !include switches.yaml

cloud:

# Enables the frontend
frontend:                                      !include frontend.yaml

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password:                                !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url:                                    panda-home.duckdns.org
  trusted_networks:
    - 172.30.32.0/23
    - 127.0.0.1
    - 192.168.1.0/24
  ip_ban_enabled:                              True
  login_attempts_threshold:                    10

# Checks for available updates
# Note:                                        This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components:                   true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default:                                     info
  logs:
    homeassistant.components.mqtt:             debug

map:

# Track the sun
sun:

# Text to speech
tts:
  - platform:                                  google

mqtt:
  broker:                                      192.168.1.200
  port:                                        1883
  client_id:                                   PandaPad_Main
  username:                                    !secret mqtt_user
  password:                                    !secret mqtt_password
  discovery:                                   true
  discovery_prefix:                            homeassistant

notify:
  - name:                                      Discord_Notify
    platform:                                  discord
    token:                                     !secret discord_token
  - name:                                      HTML5_Notify
    platform:                                  html5
    gcm_api_key:                               !secret gcm_api_key
    gcm_sender_id:                             !secret gcm_sender_id

device_tracker:
  - platform:                                  owntracks_http
  - platform:                                  nmap_tracker
    hosts:                                     192.168.1.0/24
    home_interval:                             10
    interval_seconds:                          60
    new_device_defaults:
      track_new_devices:                       False
  - platform:                                  google_maps
    username:                                  !secret google_maps_username
    password:                                  !secret google_maps_password
  - platform:                                  ping
    count:                                     5
    hosts:
      oneplus_one:                             192.168.1.64
      galaxy_s5:                               192.168.1.166

discovery:

recorder:
  purge_interval:                              1
  purge_keep_days:                             14

google_assistant:
  project_id:                                  panda-pad-home
  client_id:                                   !secret google_client_id
  access_token:                                !secret google_access_token
  api_key:                                     !secret google_api_key

zwave:
  usb_path:                                    /dev/ttyACM1
  device_config:
    light.ge_14294_inwall_smart_dimmer_level:
      refresh_value:                           true
      delay:                                   5

# commands from HA to turn on/off disco lights
shell_command:
  disco_off:                                   echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/ttyACM0
  disco_on:                                    echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/ttyACM0
  health_check:                                curl --retry 3 https://hc-ping.com/33aee216-ff26-47ee-9627-1e29985f0336

panel_iframe:
  nodered:
    title:                                     'Node-RED'
    url:                                       'https://panda-node-red.duckdns.org/'
    icon:                                      mdi:sitemap
