homeassistant:
  customize: !include customize.yaml
  elevation: 85
  latitude: !secret latitude
  longitude: !secret longitude
  name: PandaPad
  packages: !include_dir_named packages
  time_zone: America/New_York
  unit_system: imperial
  allowlist_external_dirs:
    - "/config"
    - "/config/motion"

config:
conversation:

default_config:

discovery:

history:

http:
  ip_ban_enabled: True
  login_attempts_threshold: 10

logbook:

logger:
  default: info

map:
mobile_app:

person:
recorder:
  purge_interval: 1
  purge_keep_days: 7

sensor:
  - platform: waze_travel_time
    origin: zone.home
    destination: zone.work
    region: "US"
    name: "Work Travel Time"

sun:
system_health:

tts:
  - platform: google_translate

updater:
  include_used_components: true

zone:
  - name: "Home"
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 200
    icon: mdi:home
