- platform:         flux_led
  devices:
    192.168.1.171:
      name:         Cabinets
  effect:           true
  effect_list:
    - colorloop
    - colorjump
    - colorstrobe
    - random
    - red_fade
    - green_fade
    - blue_fade
    - yellow_fade
    - cyan_fade
    - purple_fade
    - white_fade
    - rg_cross_fade
    - rb_cross_fade
    - gb_cross_fade
    - red_strobe
    - green_strobe
    - blue_strobe
    - yellow_strobe
    - cyan_strobe
    - purple_strobe
    - white_strobe
