- platform: mqtt
  state_topic: "smartthings/Motion Sensor Downstairs/temparature/state"
  name: "Downstairs Temperature"
  unit_of_measurement: "F"
- platform: mqtt
  state_topic: "smartthings/Motion Sensor Downstairs/motion/state"
  name: "Motion Sensor Downstairs"
- platform: mqtt
  state_topic: "smartthings/Motion Sensor Downstairs/battery/state"
  name: "Motion Sensor Downstairs Battery"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/contact/state"
  name: "Front Door Sensor"
- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/battery/state"
  name: "Front Door Sensor Battery"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "location/Nathan"
  name: "Nathan Life360"
- platform: mqtt
  state_topic: "location/Nathan's Phone"
  name: "Nathan Smartthings"
  
  
- platform: template
  sensors:
    school_day:
      friendly_name: "School Day"
      value_template: >-
        {% if now().weekday() < 5 and ( now().month <= 5 or now().month >= 9 ) and is_state('input_boolean.toggle_school_day','on') %}
          true
        {% else %}
          false
        {% endif %}
- platform: plex
  host: 192.168.1.65
  port: 32400
  name: Tower
  username: !secret plex_username
  password: !secret plex_password
  
- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - wind_speed
    - wind_bearing
    - apparent_temperature
    - humidity
    - pressure
    - icon
    - precip_intensity
    - precip_type

- platform: uptime

- platform: speedtest
  hour:
    - 20
  monitored_conditions:
    - ping
    - download
    - upload
    
# Failing due to issue with scan interval
#- platform: fail2ban
#  jails:
#    - ssh
#    - hass-iptables

# - platform: bayesian
  # prior: 0.1
  # probability_threshold: 0.9
  # name: nathan_home_bayesian
  # observations:
    # - entity_id: device_tracker.nathan
      # prop_given_true
