- platform: mqtt
  state_topic: "smartthings/Motion Sensor Downstairs/temparature/state"
  name: "Downstairs Temperature"
  unit_of_measurement: "F"
- platform: mqtt
  state_topic: "smartthings/Motion Sensor Downstairs/motion/state"
  name: "Motion Sensor Downstairs"
- platform: mqtt
  state_topic: "smartthings/Motion Sensor Downstairs/battery/state"
  name: "Motion Sensor Downstairs Battery"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/contact/state"
  name: "Front Door Sensor"
- platform: mqtt
  state_topic: "smartthings/Front Door Sensor/battery/state"
  name: "Front Door Sensor Battery"
  unit_of_measurement: "%"
  
- platform: template
  sensors:
    school_day:
      friendly_name: "School Day"
      value_template: >-
        {% if now().weekday() < 5 and ( now().month <= 5 or now().month >= 9 ) and is_state('input_boolean.toggle_school_day','on') %}
          true
        {% else %}
          false
        {% endif %}
- platform: plex
  host: 192.168.1.65
  port: 32400
  name: Tower
  username: zybron
  password: Zybron2000_ple
  
- platform: darksky
  api_key: c92e8e98d7153b94db7bb134685dee7e
  monitored_conditions:
    - summary
    - precip_probability
    - temperature
    - wind_speed
    - wind_bearing
    - apparent_temperature
    - humidity
    - pressure
    - icon
    - precip_intensity
    - precip_type

- platform: uptime

- platform: speedtest
  hour:
    - 20
  monitored_conditions:
    - ping
    - download
    - upload