- platform:                                mqtt
  state_topic:                             "location/Nathan"
  name:                                    "Nathan Life360"
- platform:                                mqtt
  state_topic:                             "location/Nathan's Phone"
  name:                                    "Nathan Smartthings"
- platform:                                mqtt
  state_topic:                             "location/Erin"
  name:                                    "Erin Life360"
- platform:                                mqtt
  state_topic:                             "location/Erin's Phone"
  name:                                    "Erin Smartthings"


- platform:                                template
  sensors:
    nathan_home:
      friendly_name:                       "Nathan Home"
      value_template:                      >-
        {% if is_state('device_tracker.nathan_nathan','home') %}
          home
        {% else %}
          not_home
        {% endif %}
    erin_home:
      friendly_name:                       "Erin Home"
      value_template:                      >-
        {% if is_state('device_tracker.erin_erin','home') %}
          home
        {% else %}
          not_home
        {% endif %}
    garage_door_changed:
      friendly_name:                       "Garage Door Changed"
      value_template:                      '{{ as_timestamp(states.sensor.garage_door.last_updated) | timestamp_custom("%m-%d-%Y %H:%M:%S", true) }}'
    front_door_sensor:
      friendly_name:                       'Front Door Sensor'
      value_template:                      >-
        {% if is_state('binary_sensor.sensor','on') %}
          open
        {% else %}
          closed
        {% endif %}
    front_door_sensor_battery:
      friendly_name:                       'Front Door Sensor Battery'
      value_template:                      '{{ states.zwave.front_door_sensor.attributes.battery_level }}'
      unit_of_measurement:                 '%'
    motion_sensor_downstairs:
      friendly_name:                       'Motion Sensor Downstairs'
      value_template:                      >-
        {% if states.sensor.alarm_level_2.state | float > 20 %}
          active
        {% else %}
          inactive
        {% endif %}
    motion_sensor_downstairs_temperature:
      friendly_name:                       'Downstairs Temperature'
      value_template:                      '{{ states.sensor.vision_zp3102_pir_motion_sensor_temperature.state | float }}'
      unit_of_measurement:                 '°F'
    motion_sensor_downstairs_battery:
      friendly_name:                       'Motion Sensor Downstairs Battery'
      value_template:                      '{{ states.zwave.motion_sensor_downstairs.attributes.battery_level }}'
      unit_of_measurement:                 '%'

- platform:                                plex
  host:                                    192.168.1.65
  port:                                    32400
  name:                                    Tower
  username:                                !secret plex_username
  password:                                !secret plex_password

- platform:                                wunderground
  api_key:                                 !secret weather_underground_api_key
  monitored_conditions:
    - alerts
    - dewpoint_f
    - dewpoint_string
    - feelslike_f
    - feelslike_string
    - heat_index_f
    - heat_index_string
    - elevation
    - location
    - observation_time
    - precip_today_in
    - precip_today_string
    - precip_1d_in
    - precip_1d
    - pressure_in
    - pressure_mb
    - pressure_trend
    - relative_humidity
    - solarradiation
    - temperature_string
    - temp_f
    - temp_high_record_f
    - temp_low_record_f
    - temp_high_avg_f
    - temp_low_avg_f
    - temp_high_1d_f
    - temp_low_1d_f
    - UV
    - visibility_mi
    - weather
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
    - weather_1h
    - wind_degrees
    - wind_dir
    - wind_gust_mph
    - wind_gust_1d_mph
    - wind_mph
    - wind_1d_mph
    - wind_string

- platform:                                uptime

- platform:                                mqtt
  name:                                    'Garage Door'
  state_topic:                             'garadget/garage/status'
  value_template:                          '{{ value_json.status }}'

- platform:                                mqtt
  name:                                    'Garage Brightness'
  state_topic:                             'garadget/garage/status'
  unit_of_measurement:                     '%'
  value_template:                          '{{ value_json.bright }}'

- platform:                                mqtt
  name:                                    'Garage Door Sensor'
  state_topic:                             'garadget/garage/status'
  unit_of_measurement:                     '%'
  value_template:                          '{{ value_json.sensor }}'

- platform:                                mqtt
  name:                                    'Garagdet Connection'
  state_topic:                             'garadget/garage/status'
  unit_of_measurement:                     'dB'
  value_template:                          '{{ value_json.signal }}'

- platform:                                mqtt
  name:                                    'Living Room TV'
  state_topic:                             'plex/'
  value_template:                          >-
    {% if (value_json.player == "TCLRoku TV - 2N008T166798") %}
      {{value_json.state}}
    {% endif %}
  json_attributes:
    - user
    - full_title

- platform:                                systemmonitor
  resources:
    - type:                                disk_use_percent
      arg:                                 /
    - type:                                disk_use
      arg:                                 /
    - type:                                disk_free
      arg:                                 /
    - type:                                memory_use_percent
    - type:                                memory_use
    - type:                                memory_free
    - type:                                swap_use_percent
    - type:                                swap_use
    - type:                                swap_free
    - type:                                load_1m
    - type:                                load_5m
    - type:                                load_15m
    - type:                                network_in
      arg:                                 wlan0
    - type:                                network_out
      arg:                                 wlan0
    - type:                                ipv4_address
      arg:                                 wlan0
    - type:                                processor_use
    - type:                                process
      arg:                                 hass
    - type:                                process
      arg:                                 mosquitto
    - type:                                last_boot
    - type:                                since_last_boot

- platform:                                command_line
  name:                                    CPU Temp
  command:                                 "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement:                     "°C"
  value_template:                          '{{ value | multiply(0.001) }}'

- platform:                                time_date
  display_options:
      - 'time'
      - 'date'
      - 'date_time'

- platform:                                life360
  username:                                !secret life360_username
  password:                                !secret life360_password
  mqtt_topic:                              '/life360/data'
  scan_interval:                           60

# Failing due to issue with scan interval
#- platform:                               fail2ban
#  jails:
#    - ssh
#    - hass-iptables
