- platform:              plex
  host:                  192.168.1.65
  port:                  32400
  name:                  Tower
  username:              !secret plex_username
  password:              !secret plex_password

- platform:              wunderground
  api_key:               !secret weather_underground_api_key
  monitored_conditions:
    - alerts
    - dewpoint_f
    - dewpoint_string
    - feelslike_f
    - feelslike_string
    - heat_index_f
    - heat_index_string
    - elevation
    - location
    - observation_time
    - precip_today_in
    - precip_today_string
    - precip_1d_in
    - precip_1d
    - pressure_in
    - pressure_mb
    - pressure_trend
    - relative_humidity
    - solarradiation
    - temperature_string
    - temp_f
    - temp_high_record_f
    - temp_low_record_f
    - temp_high_avg_f
    - temp_low_avg_f
    - temp_high_1d_f
    - temp_low_1d_f
    - UV
    - visibility_mi
    - weather
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
    - wind_degrees
    - wind_dir
    - wind_gust_mph
    - wind_gust_1d_mph
    - wind_mph
    - wind_1d_mph
    - wind_string

- platform:              mqtt
  name:                  'Dakota Bedroom TV'
  state_topic:           'plex/Roku Stick - 2L649C198656'
  value_template:        '{{value_json.state}}'
  json_attributes:
    - user
    - full_title
    - library_name

- platform:              mqtt
  state_topic:           'message/broadcast'
  value_template:        '{{value_json.message}}'
  json_attributes:
    - time
  name:                  'Last Message'

- platform:              mqtt
  state_topic:           'message/notification'
  value_template:        '{{value_json.message}}'
  json_attributes:
    - time
  name:                  'Last Notification'

# Failing due to issue with scan interval
#- platform:             fail2ban
#  jails:
#    - ssh
#    - hass-iptables
