- platform:                mqtt
  switches:
    zigbee2mqtt_pairing:
      command_topic:       'zigbee2mqtt/bridge/config/permit_join'
      availability_topic:  'zigbee2mqtt/bridge/state'
      name:                'Zigbee Pairing'
      qos:                 2
