version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: mv travis_secrets.yaml secrets.yaml
          name: Rename secrets file
      - run:
          command: pip install homeassistant
          name: Install Home Assistant
      - run:
          command: hass --version
          name: Version check
      - run:
          command: hass -c . --script check_config
          name: Config check
  deploy:
    steps:
      - run:
          command: sudo apt-get install -y curl
          name: Install curl
      - run:
          command: curl -X POST -H "Authorization: Bearer $HAToken" -H "Content-Type: application/json" -d '{"payload": "$CIRCLE_BUILD_NUM PASS", "topic": "circleci/status", "retain": "True"}' $HOST/api/services/mqtt/publish
          name: Publish Success

workflows:
  main:
    jobs:
      - build-and-test
      - deploy
          requires: build-and-test
