version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.8.7
    steps:
      - run:
          command: ls /config
          name: List current /config folder
      - checkout
      - run:
          command: mv travis_secrets.yaml secrets.yaml
          name: Rename secrets file
      - run:
          command: pip install homeassistant
          name: Install Home Assistant
      - run:
          command: hass --version
          name: Version check
      - run:
          command: hass -c . --script check_config
          name: Config check
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run:
          command: sudo apt-get install -y curl
          name: Install curl
      - run:
          command: >
            curl -X POST -H "Authorization: Bearer $HATOKEN" -H "Content-Type: application/json" -d '{"entity_id":"automation.pull_new_config"}' $HOST/api/services/automation/trigger
          name: Publish Success

workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
