- id:                 DailyBackup
  alias:              'Daily Backup'
  initial_state:      on
  trigger:
  - platform:         time
    at:               '03:00:00'
  action:
    - service:        hassio.snapshot_full
      data_template:
        name:         Automated Backup {{ now().strftime('%Y-%m-%d') }}

- id:                 UploadBackup
  alias:              'Upload Backup'
  initial_state:      on
  trigger:
  - platform:         time
    at:               '04:00:00'
  action:
    - service:        hassio.addon_stdin
      data_template:
        name:         '{"addon":"7be23ff5_dropbox_sync","input":{"command":"upload"}}'
