- id:                DailyBackup
  alias:             'Daily Backup'
  initial_state:     on
  trigger:
  - platform:        time
    at:              '03:00:00'
  action:
    - service:       hassio.snapshot_full
      data_template:
        name:        Automated Backup {{ now().strftime('%Y-%m-%d') }}

- id:                UploadBackup
  alias:             'Upload Backup'
  initial_state:     on
  trigger:
  - platform:        time
    at:              '04:00:00'
  action:
    - service:       hassio.addon_stdin
      data:
        addon:       '7be23ff5_dropbox_sync'
        input:       {"command":"upload"}

- id:                PullNewConfig
  alias:             'Pull New Config'
  initial_state:     on
  trigger:
  - platform:        state
    entity_id:       sensor.zybronhomeassistantconfig_last_build_state
    to:              'passed'
  condition:
    condition:       state
    entity_id:       input_boolean.new_config
    state:           'on'
  action:
    - service:       input_boolean.turn_off
      data:
        entity_id:   input_boolean.new_config
    - service:       hassio.addon_stop
      data:
        addon:       'core_git_pull'
    - delay:         '00:01:00'
    - service:       hassio.addon_start
      data:
        addon:       'core_git_pull'

- id:                SetNewConfigTesting
  alias:             'Set New Config In Testing'
  initial_state:     on
  trigger:
  - platform:        state
    entity_id:       sensor.zybronhomeassistantconfig_last_build_id
  action:
    - service:       input_boolean.turn_on
      data:
        entity_id:   input_boolean.new_config
