# LED effects
- alias:              LED Effects
  initial_state:      on
  trigger:
    - platform:       state
      entity_id:      input_select.led_effects
  action:
    - service:        light.turn_on
      data_template:
        entity_id:    light.main_balcony
        effect:       '{{ states.input_select.led_effects.state }}'
    - service:        input_select.select_option
      data:
        entity_id:    input_select.current_led_effect
        option:       '{{ states.input_select.led_effects.state }}'

- id:                 EveningLightOnBalcony
  alias:              "Turn On Lights Daily - Balcony"
  initial_state:      on
  trigger:
  - platform:         sun
    event:            sunset
    offset:           '-00:45:00'
  action:
    - service:        light.turn_on
      data:
        entity_id:    light.main_balcony
        effect:       cyan_fade

- id:                 EveningLightOffBalcony
  alias:              "Turn Off Balcony Lights Daily"
  initial_state:      on
  trigger:
  - platform:         time
    at:               '22:00:00'
  action:
    - service:        light.turn_off
      entity_id:      light.main_balcony
