#Daily light automations
- id:                MorningLightOn
  alias:             "Turn On Lights Daily - Morning"
  trigger:
  - platform:        time
    at:              '07:00:00'
  action:
    - service:       light.turn_on
      entity_id:     light.top_stairs

- id:                MorningLightOff
  alias:             "Turn Off Lights Daily - Morning"
  trigger:
  - platform:        sun
    event:           sunrise
    offset:          '00:45:00'
  action:
    - service:       light.turn_off
      entity_id:     light.top_stairs

- id:                EveningLightOn
  alias:             "Turn On Lights Daily - Evening"
  trigger:
  - platform:        sun
    event:           sunset
    offset:          '-00:45:00'
  action:
    - service:       light.turn_on
      entity_id:     light.top_stairs

- id:                EveningLightOffWeekday
  alias:             "Turn Off Lights Daily - Weekday Evening"
  trigger:
  - platform:        time
    at:              '22:00:00'
  condition:
    condition:       template
    value_template:  '{{ now().weekday() < 5 }}'
  action:
    - service:       light.turn_off
      entity_id:     light.top_stairs

- id:                EveningLightOffWeekend
  alias:             "Turn Off Lights Daily - Weekend Evening"
  trigger:
  - platform:        time
    at:              '23:00:00'
  condition:
    condition:       template
    value_template:  '{{ now().weekday() == 0 or now().weekday() >= 5 }}'
  action:
    - service:       light.turn_off
      entity_id:     light.top_stairs
