# Grandfather clock
- id:                        GrandfatherClock
  alias:                     Grandfather Clock
  initial_state:             on
  trigger:
    - platform:              time
      minutes:               00
      seconds:               00
  condition:
    - condition:             time
      after:                 '08:00:00'
      before:                '22:00:00'
    - condition:             template
      value_template:        >
        {% if is_state('media_player.kitchen_speaker', 'playing') %}
          false
        {% else %}
          true
        {% endif %}
  action:
    - service:               media_player.turn_on
      entity_id:             media_player.kitchen_speaker
    - service:               media_player.volume_set
      entity_id:
        - media_player.kitchen_speaker
      data:
        volume_level:        0.4
    - service:               media_player.play_media
      data_template:
        entity_id:
          - media_player.kitchen_speaker
        media_content_id:    https://panda-home.duckdns.org/local/grandfather-clock-chime-{{now().strftime("%I")}}.mp3
        media_content_type:  music
