# LED effects
# - alias:           LED Effects
#   trigger:
#     - platform:    state
#       entity_id:   input_select.led_effects
#   action:
#     - service:     light.turn_on
#       data_template:
#         entity_id: light.main_balcony
#         effect:    '{{ states.input_select.led_effects.state }}'
#     - service:     input_select.select_option
#       data:
#         entity_id: input_select.current_led_effect
#         option:    '{{ states.input_select.led_effects.state }}'

- id:                EveningLightOnCabinets
  alias:             "Turn On Lights Daily - Cabinets"
  trigger:
  - platform:        sun
    event:           sunset
    offset:          '-00:45:00'
  action:
    - service:       light.turn_on
      data:
        entity_id:   light.cabinets
        rgb_color:   [0,255,255]
        transition:  60 

- id:                EveningLightOffCabinets
  alias:             "Turn Off Lights Daily - Cabinets"
  trigger:
  - platform:        time
    at:              '22:00:00'
  action:
    - service:       light.turn_off
      entity_id:     light.cabinets

- id:                MorningLightOffCabinets
  alias:             "Turn Off Lights Daily Morning - Cabinets"
  trigger:
  - platform:        sun
    event:           sunrise
    offset:          '01:00:00'
  action:
    - service:       light.turn_off
      entity_id:     light.cabinets
      transition:    60

- id:                MorningLightNonSchoolDayCabinets
  alias:             "Turn On Lights Daily Morning - Cabinets"
  trigger:
  - platform:        time
    at:              '07:00:00'
  action:
    - service:       light.turn_on
      data:
        entity_id:   light.cabinets
        rgb_color:   [0,255,255]
        transition:  60
