# Notifications
- id:                   HomeAssistantStartup
  alias:                HomeAssistantStartup
  initial_state:        on
  trigger:
  - event:              start
    platform:           homeassistant
  action:
  - service:            frontend.set_theme
    data:
      name:             dark_theme
  - service:            script.store_message
    data:
      message:          'PandaPadMain is starting.'
      topic:            'notification'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: PandaPadMain is starting.'
    data:
      data:
        tag:            home_assistant_notification

- id:                   HomeAssistantShutdown
  alias:                HomeAssistantShutdown
  initial_state:        on
  trigger:
  - event:              shutdown
    platform:           homeassistant
  action:
  - service:            script.store_message
    data:
      message:          'PandaPadMain is shutting down.'
      topic:            'notification'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: PandaPadMain is shutting down.'
    data:
      data:
        tag:            home_assistant_notification

# Updater Notification
- id:                   UpdateAvailable
  alias:                "Update Notification"
  initial_state:        on
  trigger:
  - platform:           state
    entity_id:          updater.updater
  action:
  - service:            persistent_notification.create
    data:
      message:          'There is an update available for Home Assistant.'
      title:            'Home Assistant Update'
      notification_id:  'Update'
  - service:            script.store_message
    data:
      message:          'There is an update available for Home Assistant.'
      topic:            'notification'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: There is an update available for Home Assistant'
    data:
      data:
        tag:            home_asssitant_update_notification
