# Notifications
- id:                   HomeAssistantStartup
  alias:                HomeAssistantStartup
  initial_state:        on
  trigger:
  - event:              start
    platform:           homeassistant
  action:
  - service:            frontend.set_theme
    data:
      name:             dark_theme
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: PandaPadMain is starting'
    data:
      data:
        tag:            home_assistant_notification

- id:                   HomeAssistantShutdown
  alias:                HomeAssistantShutdown
  initial_state:        on
  trigger:
  - event:              shutdown
    platform:           homeassistant
  action:
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: PandaPadMain is shutting down'
    data:
      data:
        tag:            home_assistant_notification

- id:                   FrontDoorOpen
  alias:                "Front Door Open"
  initial_state:        on
  trigger:
  - platform:           state
    entity_id:          sensor.front_door_sensor
    to:                 open
    for:
      minutes:          2
  action:
  - service:            script.speech_processing
    data_template:
      speech_message:   'The front door was left open!'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: The front door was left open!'
    data:
      data:
        tag:            front_door_notification

- id:                   FrontDoorOpened
  alias:                "Front Door Opened"
  initial_state:        on
  trigger:
  - platform:           state
    entity_id:          sensor.front_door_sensor
    to:                 open
  action:
  - service:            script.speech_processing
    data_template:
      speech_message:   'The front door opened.'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: The front door opened.'
    data:
      data:
        tag:            front_door_notification

- id:                   FrontDoorClosed
  alias:                "Front Door Closed"
  initial_state:        on
  trigger:
  - platform:           state
    entity_id:          sensor.front_door_sensor
    to:                 closed
  action:
  - service:            script.speech_processing
    data_template:
      speech_message:   'The front door closed.'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: The front door closed.'
    data:
      data:
        tag:            front_door_notification

# Updater Notification
- id:                   UpdateAvailable
  alias:                "Update Notification"
  initial_state:        on
  trigger:
  - platform:           state
    entity_id:          updater.updater
  action:
  - service:            persistent_notification.create
    data:
      message:          'There is an update available for Home Assistant.'
      title:            'Home Assistant Update'
      notification_id:  'Update'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: There is an update available for Home Assistant'
    data:
      data:
        tag:            home_asssitant_update_notification

- id:                   GarageDoorLeftOpen
  alias:                "Garage Door Left Open"
  initial_state:        on
  trigger:
  - platform:           state
    entity_id:          sensor.garage_door
    to:                 open
    for:
      minutes:          5
  action:
  - service:            script.speech_processing
    data_template:
      speech_message:   'The garage door was left open.'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: The garage door was left open.'
    data:
      data:
        actions:
          - action:     "close_garage_door"
            title:      "Close Garage Door"
        tag:            garage_door_notification

- id:                   GarageDoorOpen
  alias:                "Garage Door Open"
  initial_state:        on
  trigger:
  - platform:           state
    entity_id:          sensor.garage_door
    to:                 open
  action:
  - service:            script.speech_processing
    data_template:
      speech_message:   'The garage door is open.'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: The garage door is open.'
    data:
      data:
        actions:
          - action:     "close_garage_door"
            title:      "Close Garage Door"
        tag:            garage_door_notification

- id:                   GarageDoorClosed
  alias:                "Garage Door Closed"
  initial_state:        on
  trigger:
  - platform:           state
    entity_id:          sensor.garage_door
    to:                 closed
  action:
  - service:            script.speech_processing
    data_template:
      speech_message:   'The garage door is closed.'
  - service:            notify.html5_notify
    data_template:
      message:          '{{ states.sensor.date__time.state }}: The garage door is closed.'
    data:
      data:
        tag:            garage_door_notification

- id:                   CloseGarageDoorClicked
  alias:                "Close Garage Door Clicked"
  initial_state:        on
  trigger:
  - platform:           event
    event_type:         html5_notification.clicked
    event_data:
      action:           close_garage_door
  action:
  - service:            cover.close_cover
    entity_id:          'cover.garage_door'

- id:                   LateArrivalNotificationClicked
  alias:                "Late Arrival Notification Clicked"
  initial_state:        on
  trigger:
  - platform:           event
    event_type:         html5_notification.clicked
    event_data:
      action:           turn_off_lights
  action:
  - service:            light.turn_off
    entity_id:
      - light.her_light
      - light.his_light
  - service:            light.turn_off
    entity_id:          light.cabinets
