# Presence automations
- id:                    ToggleErinAway
  alias:                 Toggle Erin Away
  initial_state:         on
  trigger:
  - platform:            state
    entity_id:           sensor.erin_home
    to:                  'not_home'
    for:
      minutes:           5
  action:
  - service:             input_boolean.turn_on
    data:
      entity_id:         input_boolean.erin_away

- id:                    ToggleNathanAway
  alias:                 Toggle Nathan Away
  initial_state:         on
  trigger:
  - platform:            state
    entity_id:           sensor.nathan_home
    to:                  'not_home'
    for:
      minutes:           5
  action:
  - service:             input_boolean.turn_on
    data:
      entity_id:         input_boolean.nathan_away

- id:                    ErinReturnHomeNotification
  alias:                 "Erin Arrives - Notification"
  initial_state:         on
  trigger:
  - platform:            state
    entity_id:           sensor.erin_home
    to:                  'home'
  condition:
    condition:           and
    conditions:
    - condition:         state
      entity_id:         input_boolean.erin_away
      state:             'on'
    - condition:         time
      before:            '22:00:00'
      after:             '08:00:00'
  action:
  - service:             tts.google_say
    entity_id:           media_player.kitchen_speaker
    data:
      message:           'Erin is arriving home.'
  - service:             input_boolean.turn_off
    data:
      entity_id:         input_boolean.erin_away

- id:                    NathanReturnHomeNotification
  alias:                 "Nathan Arrives - Notification"
  initial_state:         on
  trigger:
  - platform:            state
    entity_id:           sensor.nathan_home
    to:                  'home'
  condition:
    condition:           and
    conditions:
    - condition:         state
      entity_id:         input_boolean.nathan_away
      state:             'on'
    - condition:         time
      before:            '22:00:00'
      after:             '08:00:00'
  action:
  - service:             tts.google_say
    entity_id:           media_player.kitchen_speaker
    data:
      message:           'Nathan is arriving home.'
  - service:             input_boolean.turn_off
    data:
      entity_id:         input_boolean.nathan_away

- alias:                 Arrive Home Late
  initial_state:         on
  trigger:
    - platform:          state
      entity_id:         binary_sensor.carpresence
      to:                'off'
  condition:
    - condition:         time
      after:             '23:00:00'
      before:            '05:00:00'
  action:
    - service:           light.turn_on
      entity_id:
        - light.her_light
        - light.his_light
      data:
        brightness_pct:  25
    - service:           light.turn_on
      entity_id:         light.cabinets
    - delay:
        minutes:         10
    - service:           light.turn_off
      entity_id:
        - light.her_light
        - light.his_light
    - service:           light.turn_off
      entity_id:         light.cabinets
    - service:           notify.html5_notify
      data:
        message:         'Welcome home'
        data:
          actions:
            - action:    "turn_off_lights"
              title:     "Turn Off Lights"
          tag:           late_arrival_notification
