# Presence automations
- alias:                 Arrive Home Late
  initial_state:         on
  trigger:
    - platform:          state
      entity_id:         binary_sensor.carpresence
      to:                'off'
  condition:
    - condition:         time
      after:             '22:00:00'
      before:            '06:00:00'
  action:
    - service:           light.turn_on
      entity_id:
        - light.her_light
        - light.his_light
      data:
        brightness_pct:  25
    - service:           light.turn_on
      entity_id:         light.cabinets
    - delay:
        minutes:         10
    - service:           light.turn_off
      entity_id:
        - light.her_light
        - light.his_light
    - service:           light.turn_off
      entity_id:         light.cabinets
    - service:           notify.html5_notify
      data:
        message:         'Welcome home'
        data:
          actions:
            - action:    "turn_off_lights"
              title:     "Turn Off Lights"
          tag:           late_arrival_notification
