- id:             HealthCheckStatusUpdate
  alias:          'Health Check Status Update'
  initial_state:  on
  trigger:
  - platform:     time
    minutes:      '/5'
    seconds:      '00'
  action:
    - service:    shell_command.health_check
