- id:                DailyVacuumStart
  alias:             'Daily Vacuum Start'
  initial_state:     on
  trigger:
  - platform:        time
    at:              '11:00:00'
  action:
    - service:       vacuum.turn_on
      entity_id:     vacuum.xiaomi_vacuum_cleaner

- id:                VacuumStartNotification
  alias:             'Vacuum Start Notification'
  initial_state:     on
  trigger:
  - platform:        state
    entity_id:       vacuum.xiaomi_vacuum_cleaner
    to:              'on'
  action:
  - service:         script.store_message
    data:
      message:       'Mi Mi has started cleaning.'
      topic:         'notification'
  - service:         notify.html5_notify
    data_template:
      message:      '{{ states.sensor.date__time.state }}: Mi Mi has started cleaning.'
    data:
      data:
        actions:
          - action:  'vacuum_stop_cleaning'
            title:   'Stop Cleaning'
        tag:         vacuum_start_notification

- id:                VacuumStopCleaningActionClicked
  alias:             'Vacuum Stop Cleaning Action Clicked'
  initial_state:     on
  trigger:
  - platform:        event
    event_type:      html5_notification.clicked
    event_data:
      action:        vacuum_stop_cleaning
  action:
  - service:         vacuum.turn_off
    entity_id:       vacuum.xiaomi_vacuum_cleaner

- id:                VacuumStopNotification
  alias:             'Vacuum Stop Notification'
  initial_state:     on
  trigger:
  - platform:        state
    entity_id:       vacuum.xiaomi_vacuum_cleaner
    to:              'off'
  action:
  - service:         script.store_message
    data:
      message:       'Mi Mi has stopped cleaning.'
      topic:         'notification'
  - service:         notify.html5_notify
    data_template:
      message:      '{{ states.sensor.date__time.state }}: Mi Mi has stopped cleaning.'
    data:
      data:
        tag:         vacuum__stop_notification

- id:                VacuumErrorNotification
  alias:             'Vacuum Error Notification'
  initial_state:     on
  trigger:
  - platform:        template
    value_template:  >-
      {% if is_state('sensor.vacuum_cleaner_error_sensor', 'No Error') %}
        false
      {% else %}
        true
      {% endif %}
  action:
  - service:         script.store_message
    data_template:
      message:       >-
        Mi Mi has an error:
        {{ states.sensor.vacuum_cleaner_error_sensor.state }}
      topic:         'notification'
  - service:         notify.html5_notify
    data_template:
      message:       >-
        {{ states.sensor.date__time.state }}: Mi Mi has an error:
        {{ states.sensor.vacuum_cleaner_error_sensor.state }}
    data:
      data:
        actions:
          - action:  'vacuum_resume_cleaning'
            title:   'Resume Cleaning'
          - action:  'vacuum_locate'
            title:   'Locate'
        tag:         vacuum_error_notification

- id:                VacuumResumeCleaningActionClicked
  alias:             'Vacuum Resume Cleaning Action Clicked'
  initial_state:     on
  trigger:
  - platform:        event
    event_type:      html5_notification.clicked
    event_data:
      action:        vacuum_resume_cleaning
  action:
  - service:         vacuum.start_pause
    entity_id:       vacuum.xiaomi_vacuum_cleaner
    
- id:                VacuumLocateActionClicked
  alias:             'Vacuum Locate Action Clicked'
  initial_state:     on
  trigger:
  - platform:        event
    event_type:      html5_notification.clicked
    event_data:
      action:        vacuum_locate
  action:
  - service:         vacuum.locate
    entity_id:       vacuum.xiaomi_vacuum_cleaner
  - service:         script.store_message
    data_template:
      message:       'Locate Mi Mi triggered'
      topic:         'notification'
  - service:         notify.html5_notify
    data:
      message:       'Locate Mi Mi triggered'
      data:
        actions:
          - action:  'vacuum_resume_cleaning'
            title:   'Resume Cleaning'
          - action:  'vacuum_locate'
            title:   'Locate'
        tag:         vacuum_location_notification
