homeassistant:
  customize:
    light.lamp_light:
      friendly_name: 'Lamp'

group:
  dakotas_room:
    name: Dakota's Room
    view: no
    entities:
      - light.lamp_light

sensor:
  - platform: mqtt
    name: "Dakota Bedroom TV"
    state_topic: "plex/Roku Stick - 2L649C198656"
    value_template: "{{value_json.state}}"
    json_attributes:
      - user
      - full_title
      - library_name

automation:
  - id: LampOffAtNight
    alias: "Turn Off Lamp at Night"
    initial_state: on
    trigger:
      - platform: time
        at: "00:00:00"
    condition:
      condition: time
      weekday:
        - sun
        - mon
        - tue
        - wed
        - thu
        - fri
    action:
      service: light.turn_off
      entity_id: light.lamp_light
