homeassistant:
  customize:
    light.bottom_stairs_light:
      friendly_name:                         Bottom Stairs
    light.top_stairs_light:
      friendly_name:                         Top Stairs
    light.front_door_light:
      friendly_name:                         Front Door Light

group:
  entry:
    name:                                    Entry
    view:                                    no
    entities:
      - light.front_door_light
      - light.bottom_stairs_light
      - light.top_stairs_light

  entry_sensors:
    name:                                    Entry Sensors
    view:                                    no
    entities:
      - zwave.front_door_sensor
      - sensor.front_door_sensor
      - sensor.front_door_sensor_battery
      - zwave.motion_sensor_downstairs
      - sensor.motion_sensor_downstairs
      - sensor.motion_sensor_downstairs_temperature
      - sensor.motion_sensor_downstairs_battery
      - zwave.interior_garage_door
      - sensor.interior_garage_door
      - sensor.interior_garage_door_battery

sensor:
  - platform:                                template
    sensors:
      front_door_sensor:
        friendly_name:                       'Front Door Sensor'
        value_template:                      >-
          {% if is_state('binary_sensor.front_door_sensor','on') %}
            open
          {% else %}
            closed
          {% endif %}
      front_door_sensor_battery:
        friendly_name:                       'Front Door Sensor Battery'
        value_template:                      '{{ states.zwave.front_door_sensor.attributes.battery_level }}'
        unit_of_measurement:                 '%'
        device_class: battery
      motion_sensor_downstairs:
        friendly_name:                       'Motion Sensor Entryway'
        value_template:                      >-
          {% if states.sensor.motion_sensor_downstairs_alarm_level.state | float > 200 %}
            active
          {% else %}
            inactive
          {% endif %}
      motion_sensor_downstairs_battery:
        friendly_name:                       'Motion Sensor Entryway Battery'
        value_template:                      '{{ states.zwave.motion_sensor_downstairs.attributes.battery_level }}'
        unit_of_measurement:                 '%'
        device_class: battery
      interior_garage_door:
        friendly_name:                       'Interior Garage Door'
        value_template:                      >-
          {% if is_state('binary_sensor.interior_garage_door','on') %}
            open
          {% else %}
            closed
          {% endif %}
      interior_garage_door_battery:
        friendly_name:                       'Interior Garage Door Sensor Battery'
        value_template:                      '{{ states.zwave.interior_garage_door.attributes.battery_level }}'
        unit_of_measurement:                 '%'
        device_class: battery

automation:
  - id:                                      LightOnEntry
    alias:                                   "Turn On Light On Entry"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.motion_sensor_downstairs
      to:                                    'active'
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    'open'
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      to:                                    'open'
    action:
      service:                               light.turn_on
      entity_id:
        - light.bottom_stairs_light
        - light.top_stairs_light

  - id:                                      LightOffEntryMotion
    alias:                                   "Turn Off Light After Entry - Motion"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.motion_sensor_downstairs
      to:                                    'inactive'
      for:
        minutes:                             3
    action:
      service:                               homeassistant.turn_off
      entity_id:
        - light.bottom_stairs_light
        - light.top_stairs_light

  - id:                                      LightOffEntryDoor
    alias:                                   "Turn Off Light After Entry - Door"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    'closed'
      for:
        minutes:                             3
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      to:                                    'closed'
      for:
        minutes:                             3
    action:
      service:                               homeassistant.turn_off
      entity_id:
        - light.bottom_stairs_light
        - light.top_stairs_light

  - id:                                      FrontDoorOpen
    alias:                                   "Front Door Open"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    open
      for:
        minutes:                             2
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The front door was left open!'
    - service: notify.telegram_nathan
      data:
        title: 'Front Door'
        message: 'The front door was left open.'
    - service: notify.telegram_erin
      data:
        title: 'Front Door'
        message: 'The front door was left open.'

  - id:                                      FrontDoorOpened
    alias:                                   "Front Door Opened"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    open
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The front door opened.'
    - service: notify.telegram_nathan
      data:
        title: 'Front Door'
        message: 'The front door opened.'
    - service: notify.telegram_erin
      data:
        title: 'Front Door'
        message: 'The front door opened.'

  - id:                                      FrontDoorClosed
    alias:                                   "Front Door Closed"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      from:                                  open
      to:                                    closed
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The front door closed.'
    - service: notify.telegram_nathan
      data:
        title: 'Front Door'
        message: 'The front door closed.'
    - service: notify.telegram_erin
      data:
        title: 'Front Door'
        message: 'The front door closed.'
  
  - id:                                      InteriorGarageDoorOpen
    alias:                                   "Interior Garage Door Open"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      to:                                    open
      for:
        minutes:                             2
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The interior garage door was left open!'
    - service: notify.telegram_nathan
      data:
        title: 'Interior Garage Door'
        message: 'The interior garage door was left open.'
    - service: notify.telegram_erin
      data:
        title: 'Interior Garage Door'
        message: 'The interior garage door was left open.'

  - id:                                      InteriorGarageDoorOpened
    alias:                                   "Interior Garage Door Opened"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      to:                                    open
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The interior garage door opened.'
    - service: notify.telegram_nathan
      data:
        title: 'Interior Garage Door'
        message: 'The interior garage door opened.'
    - service: notify.telegram_erin
      data:
        title: 'Interior Garage Door'
        message: 'The interior garage door opened.'

  - id:                                      InteriorGarageDoorClosed
    alias:                                   "Interior Garage Door Closed"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      from:                                  open
      to:                                    closed
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The interior garage door closed.'
    - service: notify.telegram_nathan
      data:
        title: 'Interior Garage Door'
        message: 'The interior garage door closed.'
    - service: notify.telegram_erin
      data:
        title: 'Interior Garage Door'
        message: 'The interior garage door closed.'

  - id:                                      EveningLightOnFrontDoor
    alias:                                   "Turn On Lights Daily - Front Door"
    initial_state:                           on
    trigger:
    - platform:                              sun
      event:                                 sunset
      offset:                                '00:30:00'
    action:
      - service:                             light.turn_on
        data:
          entity_id:                         light.front_door_light

  - id:                                      EveningLightOffFrontDoor
    alias:                                   "Turn Off Front Door Light Daily"
    initial_state:                           on
    trigger:
    - platform:                              time
      at:                                    '22:00:00'
    action:
      - service:                             light.turn_off
        entity_id:                           light.front_door_light

  - id:                                      FrontDoorLightOffEntryMotion
    alias:                                   "Turn Off Front Door Light After Entry - Motion"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.motion_sensor_downstairs
      to:                                    'inactive'
      for:
        minutes:                             20
    condition:
      condition:                             and
      conditions:
        - condition:                         time
          after:                             '22:00:00'
        - condition:                         state
          entity_id:                         sun.sun
          state:                             'below_horizon'
    action:
      service:                               light.turn_off
      entity_id:                             light.front_door_light

  - id:                                      FrontDoorLightOffDoorClosed
    alias:                                   "Turn Off Front Door Light After Door Closed"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    'closed'
      for:
        minutes:                             20
    condition:
      condition:                             and
      conditions:
        - condition:                         time
          after:                             '22:00:00'
        - condition:                         state
          entity_id:                         sun.sun
          state:                             'below_horizon'
    action:
      service:                               light.turn_off
      entity_id:                             light.front_door_light

  - id:                                      FrontDoorLightOnEntry
    alias:                                   "Turn On Front Door Light On Entry"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.motion_sensor_downstairs
      to:                                    'active'
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    'open'
    condition:
      condition:                             and
      conditions:
        - condition:                         time
          after:                             '22:00:00'
        - condition:                         state
          entity_id:                         sun.sun
          state:                             'below_horizon'
    action:
      service:                               light.turn_on
      entity_id:                             light.front_door_light
