homeassistant:
  customize:
    light.bottom_stairs:
      friendly_name:                         Bottom Stairs
    light.top_stairs:
      friendly_name:                         Top Stairs
    light.front_door:
      friendly_name:                         Front Door Light

group:
  entry:
    name:                                    Entry
    view:                                    no
    entities:
      - light.front_door
      - light.bottom_stairs
      - light.top_stairs

  entry_sensors:
    name:                                    Entry Sensors
    view:                                    no
    entities:
      - zwave.front_door_sensor
      - sensor.front_door_sensor
      - sensor.front_door_sensor_battery
      - zwave.motion_sensor_downstairs
      - sensor.alarm_level_2
      - sensor.motion_sensor_downstairs
      - sensor.motion_sensor_downstairs_temperature
      - sensor.motion_sensor_downstairs_battery
      - zwave.interior_garage_door
      - sensor.interior_garage_door

sensor:
  - platform:                                template
    sensors:
      front_door_sensor:
        friendly_name:                       'Front Door Sensor'
        value_template:                      >-
          {% if is_state('binary_sensor.sensor','on') %}
            open
          {% else %}
            closed
          {% endif %}
      front_door_sensor_battery:
        friendly_name:                       'Front Door Sensor Battery'
        value_template:                      '{{ states.zwave.front_door_sensor.attributes.battery_level }}'
        unit_of_measurement:                 '%'
      motion_sensor_downstairs:
        friendly_name:                       'Motion Sensor Downstairs'
        value_template:                      >-
          {% if states.sensor.alarm_level_2.state | float > 20 %}
            active
          {% else %}
            inactive
          {% endif %}
      motion_sensor_downstairs_temperature:
        friendly_name:                       'Downstairs Temperature'
        value_template:                      '{{ states.sensor.vision_zp3102_pir_motion_sensor_temperature.state | float }}'
        unit_of_measurement:                 '°F'
      motion_sensor_downstairs_battery:
        friendly_name:                       'Motion Sensor Downstairs Battery'
        value_template:                      '{{ states.zwave.motion_sensor_downstairs.attributes.battery_level }}'
        unit_of_measurement:                 '%'
    interior_garage_door:
        friendly_name:                       'Interior Garage Door'
        value_template:                      >-
          {% if is_state('binary_sensor.interior_garage_door','on') %}
            open
          {% else %}
            closed
          {% endif %}
    interior_garage_door_battery:
        friendly_name:                       'Interior Garage Door Sensor Battery'
        value_template:                      '{{ states.zwave.interior_garage_door_sensor.attributes.battery_level }}'
        unit_of_measurement:                 '%'

automation:
  - id:                                      LightOnEntry
    alias:                                   "Turn On Light On Entry"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.motion_sensor_downstairs
      to:                                    'active'
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    'open'
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      to:                                    'open'
    action:
      service:                               light.turn_on
      entity_id:
        - light.bottom_stairs
        - light.top_stairs

  - id:                                      LightOnWhenArriving
    alias:                                   "Turn On Light On Arrival"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             cover.garage_door
      to:                                    'closed'
    condition:
      condition:                             and
      conditions:
        - condition:                         state
          entity_id:                         group.nathan
          state:                             'home'
        - condition:                         state
          entity_id:                         group.erin
          state:                             'home'
    action:
    - service:                               light.turn_on
      entity_id:
        - light.bottom_stairs
        - light.top_stairs
    - delay:
        minutes:                             3
    - service:                               light.turn_off
      entity_id:
        - light.bottom_stairs
        - light.top_stairs

  - id:                                      LightOffEntryMotion
    alias:                                   "Turn Off Light After Entry - Motion"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.motion_sensor_downstairs
      to:                                    'inactive'
      for:
        minutes:                             3
    action:
      service:                               homeassistant.turn_off
      entity_id:
        - light.bottom_stairs
        - light.top_stairs

  - id:                                      LightOffEntryDoor
    alias:                                   "Turn Off Light After Entry - Door"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    'closed'
      for:
        minutes:                             3
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      to:                                    'closed'
      for:
        minutes:                             3
    action:
      service:                               homeassistant.turn_off
      entity_id:
        - light.bottom_stairs
        - light.top_stairs

  - id:                                      FrontDoorOpen
    alias:                                   "Front Door Open"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    open
      for:
        minutes:                             2
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The front door was left open!'
    - service:                               script.store_message
      data:
        message:                             'The front door was left open!'
        topic:                               'notification'
    - service:                               notify.html5_notify
      data_template:
        message:          '{{ states.sensor.date__time.state }}: The front door was left open!'
      data:
        data:
          tag:                               front_door_notification

  - id:                                      FrontDoorOpened
    alias:                                   "Front Door Opened"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    open
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The front door opened.'
    - service:                               script.store_message
      data:
        message:                             'The front door opened.'
        topic:                               'notification'
    - service:                               notify.html5_notify
      data_template:
        message:          '{{ states.sensor.date__time.state }}: The front door opened.'
      data:
        data:
          tag:                               front_door_notification

  - id:                                      FrontDoorClosed
    alias:                                   "Front Door Closed"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      from:                                  open
      to:                                    closed
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The front door closed.'
    - service:                               script.store_message
      data:
        message:                             'The front door closed.'
        topic:                               'notification'
    - service:                               notify.html5_notify
      data_template:
        message:          '{{ states.sensor.date__time.state }}: The front door closed.'
      data:
        data:
          tag:                               front_door_notification
  
  - id:                                      InteriorGarageDoorOpen
    alias:                                   "Interior Garage Door Open"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      to:                                    open
      for:
        minutes:                             2
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The interior garage door was left open!'
    - service:                               script.store_message
      data:
        message:                             'The interior garage door was left open!'
        topic:                               'notification'
    - service:                               notify.html5_notify
      data_template:
        message:          '{{ states.sensor.date__time.state }}: The interior garage door was left open!'
      data:
        data:
          tag:                               interior_garage_door_notification

  - id:                                      InteriorGarageDoorOpened
    alias:                                   "Interior Garage Door Opened"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      to:                                    open
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The interior garage door opened.'
    - service:                               script.store_message
      data:
        message:                             'The interior garage door opened.'
        topic:                               'notification'
    - service:                               notify.html5_notify
      data_template:
        message:          '{{ states.sensor.date__time.state }}: The interior door opened.'
      data:
        data:
          tag:                               interior_garage_door_notification

  - id:                                      InteriorGarageDoorClosed
    alias:                                   "Interior Garage Door Closed"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.interior_garage_door
      from:                                  open
      to:                                    closed
    action:
    - service:                               script.speech_processing
      data_template:
        speech_message:                      'The interior garage door closed.'
    - service:                               script.store_message
      data:
        message:                             'The interior garage door closed.'
        topic:                               'notification'
    - service:                               notify.html5_notify
      data_template:
        message:          '{{ states.sensor.date__time.state }}: The interior garage door closed.'
      data:
        data:
          tag:                               interior_garage_door_notification

  - id:                                      EveningLightOnFrontDoor
    alias:                                   "Turn On Lights Daily - Front Door"
    initial_state:                           on
    trigger:
    - platform:                              sun
      event:                                 sunset
      offset:                                '00:30:00'
    action:
      - service:                             light.turn_on
        data:
          entity_id:                         light.front_door

  - id:                                      EveningLightOffFrontDoor
    alias:                                   "Turn Off Front Door Light Daily"
    initial_state:                           on
    trigger:
    - platform:                              time
      at:                                    '22:00:00'
    action:
      - service:                             light.turn_off
        entity_id:                           light.front_door

  - id:                                      FrontDoorLightOffEntryMotion
    alias:                                   "Turn Off Front Door Light After Entry - Motion"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.motion_sensor_downstairs
      to:                                    'inactive'
      for:
        minutes:                             20
    condition:
      condition:                             and
      conditions:
        - condition:                         time
          after:                             '22:00:00'
        - condition:                         state
          entity_id:                         sun.sun
          state:                             'below_horizon'
    action:
      service:                               light.turn_off
      entity_id:                             light.front_door

  - id:                                      FrontDoorLightOffDoorClosed
    alias:                                   "Turn Off Front Door Light After Door Closed"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    'closed'
      for:
        minutes:                             20
    condition:
      condition:                             and
      conditions:
        - condition:                         time
          after:                             '22:00:00'
        - condition:                         state
          entity_id:                         sun.sun
          state:                             'below_horizon'
    action:
      service:                               light.turn_off
      entity_id:                             light.front_door

  - id:                                      FrontDoorLightOnEntry
    alias:                                   "Turn On Front Door Light On Entry"
    initial_state:                           on
    trigger:
    - platform:                              state
      entity_id:                             sensor.motion_sensor_downstairs
      to:                                    'active'
    - platform:                              state
      entity_id:                             sensor.front_door_sensor
      to:                                    'open'
    condition:
      condition:                             and
      conditions:
        - condition:                         time
          after:                             '22:00:00'
        - condition:                         state
          entity_id:                         sun.sun
          state:                             'below_horizon'
    action:
      service:                               light.turn_on
      entity_id:                             light.front_door
