sensor:
  - platform:                                template
    sensors:
      front_door_sensor:
        friendly_name:                       'Front Door Sensor'
        value_template:                      >-
          {% if is_state('binary_sensor.front_door_sensor','on') %}
            open
          {% else %}
            closed
          {% endif %}
      front_door_sensor_battery:
        friendly_name:                       'Front Door Sensor Battery'
        value_template:                      '{{ states.zwave.front_door_sensor.attributes.battery_level }}'
        unit_of_measurement:                 '%'
        device_class: battery
      motion_sensor_downstairs:
        friendly_name:                       'Motion Sensor Entryway'
        value_template:                      >-
          {% if states.sensor.motion_sensor_downstairs_alarm_level.state | float > 200 %}
            active
          {% else %}
            inactive
          {% endif %}
      motion_sensor_downstairs_battery:
        friendly_name:                       'Motion Sensor Entryway Battery'
        value_template:                      '{{ states.zwave.motion_sensor_downstairs.attributes.battery_level }}'
        unit_of_measurement:                 '%'
        device_class: battery
      interior_garage_door:
        friendly_name:                       'Interior Garage Door'
        value_template:                      >-
          {% if is_state('binary_sensor.interior_garage_door','on') %}
            open
          {% else %}
            closed
          {% endif %}
      interior_garage_door_battery:
        friendly_name:                       'Interior Garage Door Sensor Battery'
        value_template:                      '{{ states.zwave.interior_garage_door.attributes.battery_level }}'
        unit_of_measurement:                 '%'
        device_class: battery

