binary_sensor:
  - platform:               bayesian
    prior:                  0.5
    probability_threshold:  0.7
    name:                   erin_home_bayesian
    observations:
      - entity_id:          device_tracker.erin_galaxys5
        platform:           'state'
        to_state:           'home'
        prob_given_true:    0.99
        prob_given_false:   0.6
      - entity_id:          device_tracker.galaxy_s5
        platform:           'state'
        to_state:           'home'
        prob_given_true:    0.99
        prob_given_false:   0.6

input_boolean:
  erin_away:
    name:                   Erin is Away
    initial:                off

automation:
  - id:                     ToggleErinAway
    alias:                  Toggle Erin Away
    initial_state:          on
    trigger:
    - platform:             state
      entity_id:            person.erin
      to:                   'not_home'
      for:
        minutes:            5
    action:
    - service:              input_boolean.turn_on
      data:
        entity_id:          input_boolean.erin_away

  - id:                     ErinReturnHomeNotification
    alias:                  "Erin Arrives - Notification"
    initial_state:          on
    trigger:
    - platform:             state
      entity_id:            person.erin
      to:                   'home'
    condition:
      condition:            and
      conditions:
      - condition:          state
        entity_id:          input_boolean.erin_away
        state:              'on'
      - condition:          time
        before:             '22:00:00'
        after:              '08:00:00'
    action:
    - service:              tts.google_translate_say
      entity_id:            media_player.kitchen_speaker
      data:
        message:            'Erin is arriving home.'
    - service:              input_boolean.turn_off
      data:
        entity_id:          input_boolean.erin_away

  - id: OpenGarageOnErinEnterHomeZone
    alias: 'Open Garage On Erin Enter Home Zone'
    initial_state: on
    trigger:
    - platform: zone
      entity_id: device_tracker.google_maps_111510462305838841156
      zone: zone.home
      event: enter
    condition:
      condition: state
      entity_id: input_boolean.erin_away
      state: 'on'
    action:
    - service: cover.open_cover
      entity_id: 'cover.garage_door'
