input_boolean:
  erin_away:
    name:                   Erin is Away
    initial:                off

sensor:
  - platform: template
    sensors:
      erin_location:
        friendly_name: "Erin's Location"
        value_template: "{{ [states.person.erin.attributes.latitude, states.person.erin.attributes.longitude] }}"

