folder_watcher:
  - folder: /config
    friendly_name: 'Config Watcher'
    patterns:
      - '*.yaml'

group:
  system_monitor:
    name:                  System Monitor
    entities:
      - sensor.cpu_temp
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.disk_use_percent
      - sensor.disk_use
      - sensor.disk_free
      - sensor.memory_use_percent
      - sensor.memory_use
      - sensor.memory_free
      - sensor.swap_use_percent
      - sensor.swap_use
      - sensor.swap_free
      - sensor.load_1m
      - sensor.load_5m
      - sensor.load_15m
      - sensor.network_in_wlan0
      - sensor.network_out_wlan0
      - sensor.ipv4_address_wlan0
      - sensor.processor_use
      - sensor.process_hass
      - sensor.process_mosquitto
      - sensor.last_boot
      - sensor.since_last_boot

rest_command:
  google_backup:
    url: 'http://localhost:8055/gb/doBackup'
    timeout: '300'

sensor:
  - platform:              command_line
    name:                  CPU Temp
    command:               'cat /sys/class/thermal/thermal_zone0/temp'
    unit_of_measurement:   '°C'
    value_template:        '{{ value | multiply(0.001) }}'
    device_class: temperature

  - platform:              time_date
    display_options:
        - 'time'
        - 'date'
        - 'date_time'

  - platform:              travisci
    api_key:               !secret travis_ci_token
    monitored_conditions:
      - last_build_id
      - last_build_state
      - state
    repository:
      - HomeAssistantConfig

shell_command:
  disco_off:               echo -e -n '\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51' > /dev/ttyACM0
  disco_on:                echo -e -n '\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50' > /dev/ttyACM0
  health_check:            curl --retry 3 https://hc-ping.com/33aee216-ff26-47ee-9627-1e29985f0336

switch:
  - platform:              mqtt
    command_topic:         'zigbee2mqtt/bridge/config/permit_join'
    state_topic:           'zigbee2mqtt/bridge/config/permit_join'
    availability_topic:    'zigbee2mqtt/bridge/state'
    name:                  'Zigbee Pairing'
    qos:                   2
    retain:                true
    payload_on:            'true'
    payload_off:           'false'

automation:
  # - id:                    DailyBackup
  #   alias:                 'Daily Backup'
  #   initial_state:         on
  #   trigger:
  #   - platform:            time
  #     at:                  '03:00:00'
  #   action:
  #     - service:           hassio.snapshot_full
  #       data_template:
  #         name:            Automated Backup {{ now().strftime('%Y-%m-%d') }}

  # - id:                    UploadBackup
  #   alias:                 'Upload Backup'
  #   initial_state:         on
  #   trigger:
  #   - platform:            time
  #     at:                  '04:00:00'
  #   action:
  #     - service:           rest_command.google_backup

  - id:                    PullNewConfig
    alias:                 'Pull New Config'
    initial_state:         on
    trigger:
    - platform:            state
      entity_id:           sensor.zybron_homeassistantconfig_last_build_state
      to:                  'passed'
    action:
      - service: notify.telegram_nathan
        data:
          title: 'Pull Config'
          message: 'Pulling new config from GitHub.'
      - service:           hassio.addon_start
        data:
          addon:           'core_git_pull'

  # Notifications
  - id:                    HomeAssistantStartup
    alias:                 HomeAssistantStartup
    initial_state:         on
    trigger:
    - event:               start
      platform:            homeassistant
    action:
    - service:             frontend.set_theme
      data:
        name:              dark_theme
    - service: notify.telegram_nathan
      data:
        title: 'Home Assistant'
        message: 'Home Assistant is starting.'
    - service: notify.telegram_erin
      data:
        title: 'Home Assistant'
        message: 'Home Assistant is starting.'

  - id:                    HomeAssistantShutdown
    alias:                 HomeAssistantShutdown
    initial_state:         on
    trigger:
    - event:               shutdown
      platform:            homeassistant
    action:
    - service: notify.telegram_nathan
      data:
        title: 'Home Assistant'
        message: 'Home Assistant is shutting down.'
    - service: notify.telegram_erin
      data:
        title: 'Home Assistant'
        message: 'Home Assistant is shutting down.'


  - id:                    HealthCheckStatusUpdate
    alias:                 'Health Check Status Update'
    initial_state:         on
    trigger:
    - platform:            time_pattern
      minutes:             '/5'
      seconds:             '0'
    action:
      - service:           shell_command.health_check
