sensor:
  - platform:              command_line
    name:                  CPU Temp
    command:               'cat /sys/class/thermal/thermal_zone0/temp'
    unit_of_measurement:   '°C'
    value_template:        '{{ value | multiply(0.001) }}'

  - platform:              time_date
    display_options:
        - 'time'
        - 'date'
        - 'date_time'

shell_command:
  disco_off:               echo -e -n '\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51' > /dev/ttyACM0
  disco_on:                echo -e -n '\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50' > /dev/ttyACM0
  health_check:            curl --retry 3 https://hc-ping.com/33aee216-ff26-47ee-9627-1e29985f0336
  pull_config: cd /config && git pull

automation:
  - id:                    PullNewConfig
    alias:                 'Pull New Config'
    initial_state:         on
    trigger:
    - platform:            state
      entity_id:           sensor.zybron_homeassistantconfig_last_build_state
      to:                  'passed'
    action:
      - service: notify.telegram_nathan
        data:
          title: 'Pull Config'
          message: 'Pulling new config from GitHub.'
      - service: shell_command.pull_config
      
  # Notifications
  - id:                    HomeAssistantStartup
    alias:                 HomeAssistantStartup
    initial_state:         on
    trigger:
    - event:               start
      platform:            homeassistant
    action:
    - service: notify.telegram_nathan
      data:
        title: 'Home Assistant'
        message: 'Home Assistant is starting.'
    - service: notify.telegram_erin
      data:
        title: 'Home Assistant'
        message: 'Home Assistant is starting.'

  - id:                    HomeAssistantShutdown
    alias:                 HomeAssistantShutdown
    initial_state:         on
    trigger:
    - event:               shutdown
      platform:            homeassistant
    action:
    - service: notify.telegram_nathan
      data:
        title: 'Home Assistant'
        message: 'Home Assistant is shutting down.'
    - service: notify.telegram_erin
      data:
        title: 'Home Assistant'
        message: 'Home Assistant is shutting down.'


  - id:                    HealthCheckStatusUpdate
    alias:                 'Health Check Status Update'
    initial_state:         on
    trigger:
    - platform:            time_pattern
      minutes:             '/5'
      seconds:             '0'
    action:
      - service:           shell_command.health_check
