group:
  kitchen:
    name:                      Kitchen
    view:                      no
    entities:
      - light.cabinets

light:
  - platform:                  flux_led
    devices:
      192.168.1.171:
        name:                  Cabinets

automation:
  - id:                        GrandfatherClock
    alias:                     Grandfather Clock
    initial_state:             on
    trigger:
      - platform:              time_pattern
        minutes:               '0'
        seconds:               '0'
    condition:
      - condition:             time
        after:                 '08:00:00'
        before:                '22:00:00'
      - condition:             template
        value_template:        >
          {% if is_state('media_player.kitchen_speaker', 'playing') %}
            false
          {% else %}
            true
          {% endif %}
    action:
      - service:               media_player.turn_on
        entity_id:             media_player.kitchen_speaker
      - service:               media_player.volume_set
        entity_id:
          - media_player.kitchen_speaker
        data:
          volume_level:        0.4
      - service:               media_player.play_media
        data_template:
          entity_id:
            - media_player.kitchen_speaker
          media_content_id:    https://ha.zybron.com/local/grandfather-clock-chime-{{now().strftime("%I")}}.mp3
          media_content_type:  music

  - id:                        EveningLightOnCabinets
    alias:                     "Turn On Lights Daily - Cabinets"
    initial_state:             on
    trigger:
    - platform:                sun
      event:                   sunset
      offset:                  '-00:45:00'
    condition:
      condition:               template
      value_template:          "{{ now().month != 10 and now().month != 12 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [0,255,255]
          transition:          60

  - id:                        EveningLightOnCabinetsHalloween
    alias:                     "Turn On Lights Daily - Cabinets - Halloween"
    initial_state:             on
    trigger:
    - platform:                sun
      event:                   sunset
      offset:                  '-00:45:00'
    condition:
      condition:               template
      value_template:          "{{ now().month == 10 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [255,40,0]
          transition:          60

  - id:                        EveningLightOnCabinetsChristmas
    alias:                     "Turn On Lights Daily - Cabinets - Christmas"
    initial_state:             on
    trigger:
    - platform:                sun
      event:                   sunset
      offset:                  '-00:45:00'
    condition:
      condition:               template
      value_template:          "{{ now().month == 12 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [0,0,255]
          transition:          60

  - id:                        EveningLightOffCabinets
    alias:                     "Turn Off Lights Daily - Cabinets"
    initial_state:             on
    trigger:
    - platform:                time
      at:                      '22:00:00'
    action:
      - service:               light.turn_off
        entity_id:             light.cabinets

  # - id:                        MorningLightOffCabinets
  #   alias:                     "Turn Off Lights Daily Morning - Cabinets"
  #   initial_state:             on
  #   trigger:
  #   - platform:                sun
  #     event:                   sunrise
  #     offset:                  '01:00:00'
  #   action:
  #     - service:               light.turn_off
  #       data:
  #         entity_id:           light.cabinets
  #         transition:          60

  - id:                        MorningLightOnCabinets
    alias:                     "Turn On Lights Daily Morning - Cabinets"
    initial_state:             on
    trigger:
    - platform:                time
      at:                      '07:00:00'
    condition:
      condition:               template
      value_template:          "{{ now().month != 10 and now().month != 12 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [0,255,255]
          transition:          60

  - id:                        MorningLightOnCabinetsHalloween
    alias:                     "Turn On Lights Daily Morning - Cabinets - Halloween"
    initial_state:             on
    trigger:
    - platform:                time
      at:                      '07:00:00'
    condition:
      condition:               template
      value_template:          "{{ now().month == 10 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [255,40,0]
          transition:          60

  - id:                        MorningLightOnCabinetsChristmas
    alias:                     "Turn On Lights Daily Morning - Cabinets - Christmas"
    initial_state:             on
    trigger:
    - platform:                time
      at:                      '07:00:00'
    condition:
      condition:               template
      value_template:          "{{ now().month == 12 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [0,0,255]
          transition:          60