group:
  kitchen:
    name:                      Kitchen
    view:                      no
    entities:
      - light.cabinets

light:
  - platform:                  flux_led
    devices:
      192.168.1.171:
        name:                  Cabinets
    effect:                    true
    effect_list:
      - colorloop
      - colorjump
      - colorstrobe
      - random
      - red_fade
      - green_fade
      - blue_fade
      - yellow_fade
      - cyan_fade
      - purple_fade
      - white_fade
      - rg_cross_fade
      - rb_cross_fade
      - gb_cross_fade
      - red_strobe
      - green_strobe
      - blue_strobe
      - yellow_strobe
      - cyan_strobe
      - purple_strobe
      - white_strobe

automation:
  - id:                        GrandfatherClock
    alias:                     Grandfather Clock
    initial_state:             on
    trigger:
      - platform:              time
        minutes:               00
        seconds:               00
    condition:
      - condition:             time
        after:                 '08:00:00'
        before:                '22:00:00'
      - condition:             template
        value_template:        >
          {% if is_state('media_player.kitchen_speaker', 'playing') %}
            false
          {% else %}
            true
          {% endif %}
    action:
      - service:               media_player.turn_on
        entity_id:             media_player.kitchen_speaker
      - service:               media_player.volume_set
        entity_id:
          - media_player.kitchen_speaker
        data:
          volume_level:        0.4
      - service:               media_player.play_media
        data_template:
          entity_id:
            - media_player.kitchen_speaker
          media_content_id:    https://panda-home.duckdns.org/local/grandfather-clock-chime-{{now().strftime("%I")}}.mp3
          media_content_type:  music

  - id:                        EveningLightOnCabinets
    alias:                     "Turn On Lights Daily - Cabinets"
    initial_state:             on
    trigger:
    - platform:                sun
      event:                   sunset
      offset:                  '-00:45:00'
    condition:
      condition:               template
      value_template:          "{{ now().month != 10 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [0,255,255]
          transition:          60

  - id:                        EveningLightOnCabinetsHalloween
    alias:                     "Turn On Lights Daily - Cabinets - Halloween"
    initial_state:             on
    trigger:
    - platform:                sun
      event:                   sunset
      offset:                  '-00:45:00'
    condition:
      condition:               template
      value_template:          "{{ now().month == 10 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [255,69,0]
          transition:          60

  - id:                        EveningLightOffCabinets
    alias:                     "Turn Off Lights Daily - Cabinets"
    initial_state:             on
    trigger:
    - platform:                time
      at:                      '22:00:00'
    action:
      - service:               light.turn_off
        entity_id:             light.cabinets

  - id:                        MorningLightOffCabinets
    alias:                     "Turn Off Lights Daily Morning - Cabinets"
    initial_state:             on
    trigger:
    - platform:                sun
      event:                   sunrise
      offset:                  '01:00:00'
    action:
      - service:               light.turn_off
        data:
          entity_id:           light.cabinets
          transition:          60

  - id:                        MorningLightOnCabinets
    alias:                     "Turn On Lights Daily Morning - Cabinets"
    initial_state:             on
    trigger:
    - platform:                time
      at:                      '07:00:00'
    condition:
      condition:               template
      value_template:          "{{ now().month != 10 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [0,255,255]
          transition:          60

  - id:                        MorningLightOnCabinetsHalloween
    alias:                     "Turn On Lights Daily Morning - Cabinets - Halloween"
    initial_state:             on
    trigger:
    - platform:                time
      at:                      '07:00:00'
    condition:
      condition:               template
      value_template:          "{{ now().month == 10 }}"
    action:
      - service:               light.turn_on
        data:
          entity_id:           light.cabinets
          rgb_color:           [255,69,0]
          transition:          60
