homeassistant:
  customize:
    light.ge_14294_inwall_smart_dimmer_level:
      friendly_name:                           Living Room Switch

group:
  living_room:
    name:                                      Living Room
    entities:
      - light.ge_14294_inwall_smart_dimmer_level
      - zwave.ge_14294_inwall_smart_dimmer

sensor:
  - platform:                                  mqtt
    name:                                      'Living Room TV'
    state_topic:                               'plex/SHIELD Android TV'
    value_template:                            '{{value_json.state}}'
    json_attributes:
      - user
      - full_title
      - library_name

automation:
  - id:                                        MorningLightOn
    alias:                                     "Turn On Lights Daily - Morning"
    initial_state:                             on
    trigger:
    - platform:                                time
      at:                                      '07:00:00'
    condition:
      condition:                               state
      entity_id:                               light.ge_14294_inwall_smart_dimmer_level
      state:                                   'off'
    action:
      - service:                               light.turn_on
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          brightness_pct:                      1
      - service:                               light.turn_on
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          brightness_pct:                      100
          transition:                          600

  - id:                                        MorningLightOff
    alias:                                     "Turn Off Lights Daily - Morning"
    initial_state:                             on
    trigger:
    - platform:                                sun
      event:                                   sunrise
      offset:                                  '00:45:00'
    condition:
      condition:                               state
      entity_id:                               light.ge_14294_inwall_smart_dimmer_level
      state:                                   'on'
    action:
      - service:                               light.turn_on
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          brightness_pct:                      0
          transition:                          600
      - delay:
          seconds:                             600
      - service:                               light.turn_off
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level

  - id:                                        EveningLightOn
    alias:                                     "Turn On Lights Daily - Evening"
    initial_state:                             on
    trigger:
    - platform:                                sun
      event:                                   sunset
      offset:                                  '-00:45:00'
    condition:
      condition:                               state
      entity_id:                               light.ge_14294_inwall_smart_dimmer_level
      state:                                   'off'
    action:
      - service:                               light.turn_on
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          brightness_pct:                      1
      - service:                               light.turn_on
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          brightness_pct:                      50
          transition:                          300

  - id:                                        EveningLightOffWeekday
    alias:                                     "Turn Off Lights Daily - Weekday Evening"
    initial_state:                             on
    trigger:
    - platform:                                state
      entity_id: binary_sensor.living_room_occupancy
      to: 'off'
    condition:
      condition:                               and
      conditions:
        - condition:                           template
          value_template:                      '{{ now().weekday() > 0 and now().weekday() < 5 }}'
        - condition:                           state
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          state:                               'on'
        - condition: time
          after: '22:00:00'
          before: '07:00:00'
    action:
      - service:                               light.turn_on
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          brightness_pct:                      0
          transition:                          300
      - delay:
          seconds:                             300
      - service:                               light.turn_off
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level

  - id:                                        EveningLightOffWeekend
    alias:                                     "Turn Off Lights Daily - Weekend Evening"
    initial_state:                             on
    trigger:
    - platform:                                state
      entity_id: binary_sensor.living_room_occupancy
      to: 'off'
    condition:
      condition:                               and
      conditions:
        - condition:                           template
          value_template:                      '{{ now().weekday() > 0 and now().weekday() < 5 }}'
        - condition:                           state
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          state:                               'on'
        - condition: time
          after: '23:00:00'
          before: '07:00:00'
    action:
      - service:                               light.turn_on
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          brightness_pct:                      0
          transition:                          300
      - delay:
          seconds:                             300
      - service:                               light.turn_off
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level

  - id:                                        'TurnOffLightsWhenMoviePlaying'
    alias:                                     'Turn off lights when a movie is playing'
    initial_state:                             on
    trigger:
    - platform:                                state
      entity_id:                               sensor.living_room_tv
      to:                                      'playing'
    condition:
      condition:                               and
      conditions:
        - condition:                           state
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          state:                               'on'
        - condition:                           sun
          after:                               sunset
    action:
      - service:                               light.turn_off
        entity_id:                             light.ge_14294_inwall_smart_dimmer_level

  - id:                                        'TurnOnLightsWhenMoviePaused'
    alias:                                     'Turn on lights when a movie is paused'
    initial_state:                             on
    trigger:
    - platform:                                state
      entity_id:                               sensor.living_room_tv
      to:                                      'paused'
    condition:
      condition:                               and
      conditions:
        - condition:                           state
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          state:                               'off'
        - condition:                           sun
          after:                               sunset
    action:
      - service:                               light.turn_on
        data:
          entity_id:                           light.ge_14294_inwall_smart_dimmer_level
          brightness_pct:                      30
