binary_sensor:
  - platform:               bayesian
    prior:                  0.5
    probability_threshold:  0.7
    name:                   nathan_home_bayesian
    observations:
      - entity_id:          device_tracker.nathan_oneplus
        platform:           'state'
        to_state:           'home'
        prob_given_true:    0.99
        prob_given_false:   0.6
      - entity_id:          device_tracker.oneplus_one
        platform:           'state'
        to_state:           'home'
        prob_given_true:    0.99
        prob_given_false:   0.6

input_boolean:
    nathan_away:
      name:                 Nathan is Away

automation:
  - id:                     ToggleNathanAway
    alias:                  Toggle Nathan Away
    initial_state:          on
    trigger:
    - platform:             state
      entity_id:            person.nathan
      to:                   'not_home'
      for:
        minutes:            5
    action:
    - service:              input_boolean.turn_on
      data:
        entity_id:          input_boolean.nathan_away

  - id:                     NathanReturnHomeNotification
    alias:                  "Nathan Arrives - Notification"
    initial_state:          on
    trigger:
    - platform:             state
      entity_id:            person.nathan
      to:                   'home'
    condition:
      condition:            and
      conditions:
      - condition:          state
        entity_id:          input_boolean.nathan_away
        state:              'on'
      - condition:          time
        before:             '22:00:00'
        after:              '08:00:00'
    action:
    - service:              tts.google_translate_say
      entity_id:            media_player.kitchen_speaker
      data:
        message:            'Nathan is arriving home.'
    - service:              input_boolean.turn_off
      data:
        entity_id:          input_boolean.nathan_away

  - id: OpenGarageOnNathanEnterHomeZone
    alias: 'Open Garage On Nathan Enter Home Zone'
    initial_state: on
    trigger:
    - platform: zone
      entity_id: device_tracker.google_maps_108648636233625132646
      zone: zone.home
      event: enter
    condition:
      condition: state
      entity_id: input_boolean.nathan_away
      state: 'on'
    action:
    - service: cover.open_cover
      entity_id: 'cover.garage_door'
