sensor:
  - platform: dnsip

automation:
  - id: UpdateIPAddressForCoH
    alias: 'Update IP Address for CoH'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.myip
    action:
      service: mqtt.publish
      data_template:
        topic: 'iotlink/workgroup/nathan-pc/commands/run'
        payload_template: >-
          { "command": "D:\\i25 Release\\updateip.bat", 
            "args": "{{ trigger.from_state.state }}, {{ trigger.to_state.state }}", 
            "path": "D:\\i25 Release\\", "user": "" }