input_boolean:
    nathan_away:
      name:                 Nathan is Away

sensor:
  - platform: template
    sensors:
      nathan_location:
        friendly_name: "Nathan's Location"
        value_template: "{{ [states.person.nathan.attributes.latitude, states.person.nathan.attributes.longitude] }}"
