group:
  plex_sensors:
    name: TV sensors
    entities:
      - sensor.plex
      - sensor.tautulli

sensor:
  - platform: tautulli
    api_key: !secret tautulli_api_key
    host: !secret tautulli_host