group:
  plex_sensors:
    name: TV sensors
    entities:
      - sensor.living_room_tv
      - sensor.master_bedroom_tv
      - sensor.dakota_bedroom_tv
      - sensor.plex_recently_added

sensor:
  - platform: plex_recently_added
    token: !secret plex_token
    server_name: 'Tower'
    ssl: false
    max: 5
    download_images: true
    ssl_cert: false
    section_types:
      - movie
      - show

automation:
  - id: 'PlexNewArrivalNotification'
    alias: 'Plex New Arrival Notification'
    trigger:
      platform: state
      entity_id: sensor.plex_recently_added
    action:
      - service: notify.discord_notify
        data_template:
          message: '{{ states.sensor.plex_recently_added.state }}'
          target: '535493793538113537'
