group:
  plex_sensors:
    name: TV sensors
    entities:
      - sensor.living_room_tv
      - sensor.master_bedroom_tv
      - sensor.dakota_bedroom_tv
      - sensor.plex_recently_added

sensor:
  - platform: plex
    host: 192.168.1.65
    port: 32400
    name: Tower
    username: !secret plex_username
    password: !secret plex_password
  - platform: tautulli
    api_key: !secret tautulli_api_key
    host: 192.168.1.65
  - platform: mqtt
    name: 'Plex Recently Added'
    state_topic: 'plex/tautulli/recently_added'
    value_template: '{{ value_json.body }}'

automation:
  - id: 'PlexNewArrivalNotification'
    alias: 'Plex New Arrival Notification'
    trigger:
      platform: state
      entity_id: sensor.plex_recently_added
    action:
      - service: notify.discord_notify
        data_template:
          message: '{{ states.sensor.plex_recently_added.state }}'
          target: '535493793538113537'
