notify:
  - name: telegram_pandahome
    platform: telegram
    chat_id: -1001184476815

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    parse_mode: html
    allowed_chat_ids:
      - 749282427
      - -1001184476815

automation:
  - id: 'TelegramTesting'
    alias: 'Telegram Testing'
    initial_state: on
    trigger:
      - platform: event
        event_type: telegram_command
        event_data:
          command: '/test'
    action:
      - service: notify.telegram_pandahome
        data:
          title: 'Test Title'
          message: 'Test message.'
          data:
            inline_keyboard:
              - 'Test:/do_test'
  
  - id: 'TelegramTestingCallback'
    alias: 'Telegram Testing Callback'
    initial_state: on
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/do_test'
    action:
      - service: notify.telegram_pandahome
        data:
          title: 'Success Title'
          message: 'Success message.'