group:
  daily_forecast:
    name:                  Daily Forecast
    entities:
      - sensor.pws_weather_1d
      - sensor.pws_weather_1n
      - sensor.pws_weather_2d
      - sensor.pws_weather_2n
      - sensor.pws_weather_3d
      - sensor.pws_weather_3n
      - sensor.pws_weather_4d
      - sensor.pws_weather_4n

  weather:
    view:                  yes
    icon:                  mdi:weather-partlycloudy
    name:                  Weather
    entities:
      - group.weather_overview
      - group.daily_forecast

  weather_overview:
    name:                  Weather overview
    entities:
      - sensor.pws_weather
      - sensor.pws_temp_f
      - sensor.pws_feelslike_f
      - sensor.pws_temp_high_record_f
      - sensor.pws_temp_low_record_f
      - sensor.pws_precip_1d
      - sensor.pws_precip_1d_in
      - sensor.pws_wind_mph
      - sensor.pws_wind_1d_mph
      - sensor.pws_uv
      - sensor.pws_alerts

sensor:
  - platform:              wunderground
    api_key:               !secret weather_underground_api_key
    monitored_conditions:
      - alerts
      - dewpoint_f
      - dewpoint_string
      - feelslike_f
      - feelslike_string
      - heat_index_f
      - heat_index_string
      - elevation
      - location
      - observation_time
      - precip_today_in
      - precip_today_string
      - precip_1d_in
      - precip_1d
      - pressure_in
      - pressure_mb
      - pressure_trend
      - relative_humidity
      - solarradiation
      - temperature_string
      - temp_f
      - temp_high_record_f
      - temp_low_record_f
      - temp_high_avg_f
      - temp_low_avg_f
      - temp_high_1d_f
      - temp_low_1d_f
      - UV
      - visibility_mi
      - weather
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
      - wind_degrees
      - wind_dir
      - wind_gust_mph
      - wind_gust_1d_mph
      - wind_mph
      - wind_1d_mph
      - wind_string
