---
name: Home Assistant CI
# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
jobs:
#  yamllint:
#    name: "Yamllint"
#    runs-on: ubuntu-latest
#    steps:
#      - name: Getting your configuration from GitHub
#        uses: actions/checkout@v1
#      - name: Running YAMLlint
#        uses: "docker://pipelinecomponents/yamllint:latest"
#        with:
#          args: yamllint -f parsable -d relaxed .
  remarklint:
    name: "Remarklint"
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: >
            "remark --no-stdout --color --frail
            --use preset-lint-recommended ."
  home_assistant_stable:
    name: "Home-Assistant: Stable"
    runs-on: ubuntu-latest
    needs: remarklint
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Copy test secrets file to secrets.yaml
        run: cp travis_secrets.yaml secrets.yaml
      - name: Home Assistant Version
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: >
            python -m homeassistant --version
      - name: Home Assistant Check
        uses: "docker://homeassistant/home-assistant:stable"
        with:
          args: python -m homeassistant --config . --script check_config --info all
